# ==============================================================================
# SDC Constraints for ascan module
# ==============================================================================
# Note: Clocks (sys_clk and adc_clk) are generated by the PLL and defined
# in the PLL's SDC file. This SDC file references those clocks.

# 1. Свойства тактовых частот (Clock Uncertainty)
# Автоматический расчет джиттера и погрешностей тактовых сигналов
derive_clock_uncertainty

# 2. Асинхронные отношения между доменами (CDC - Clock Domain Crossing)
# Так как домены sys_clk (80MHz) и adc_clk (65MHz) асинхронны по определению,
# все пути между ними исключаются из стандартного тайминг-анализа.
set_clock_groups -asynchronous \
    -group [get_clocks {sys_clk}] \
    -group [get_clocks {adc_clk}]

# 3. Ограничения на входные порты (Input Delays)
# Входные сигналы в домене adc_clk (65 MHz, период ~15.38 ns)
# i_adc_sync и i_n_samples приходят из синхронных модулей sync_cc и adc_latch_param
set_input_delay -clock [get_clocks {adc_clk}] -max 4.000 [get_ports {i_in_data[*] i_adc_sync i_n_samples[*]}]
set_input_delay -clock [get_clocks {adc_clk}] -min 0.500 [get_ports {i_in_data[*] i_adc_sync i_n_samples[*]}]

# Входные сигналы в домене sys_clk (80 MHz, период 12.5 ns)
# i_out_rdy приходит от внешнего приемника данных
set_input_delay -clock [get_clocks {sys_clk}] -max 3.500 [get_ports {i_out_rdy}]
set_input_delay -clock [get_clocks {sys_clk}] -min 0.500 [get_ports {i_out_rdy}]

# 4. Ограничения на выходные порты (Output Delays)
# Выходные сигналы в домене sys_clk (80 MHz, период 12.5 ns)
set_output_delay -clock [get_clocks {sys_clk}] -max 3.500 [get_ports {o_data_ready o_out_size[*] o_out_data[*] o_out_vld}]
set_output_delay -clock [get_clocks {sys_clk}] -min -0.500 [get_ports {o_data_ready o_out_size[*] o_out_data[*] o_out_vld}]

# 5. Исключения таймингов (CDC False Paths)

# Сбросы sys_rst_n и adc_rst_n НЕ объявляются как false path!
# Они приходят из sync_cc синхронизированными, и для них важен анализ Recovery/Removal.

# Путь асинхронного флага CDC (write_done_toggle [adc_clk] -> wr_done_sync0 [sys_clk])
# Исключаем из анализа, так как далее стоит классическая схема синхронизации из 3 триггеров
set_false_path -to [get_registers {*wr_done_sync0}]

# Исключение путей для стабильных данных размера страниц (Quasi-static CDC)
# Регистры ram_page_size_0/1 изменяются только в домене adc_clk, но считываются в sys_clk.
# Чтение происходит строго после завершения полной CDC-синхронизации события wr_done_sync,
# поэтому данные на шине гарантированно стабильны.
set_false_path -from [get_registers {*ram_page_size_*}] -to [get_registers {*o_out_size[*]}]